name: Validate Deleted File's SHA256 Hash

on:
  pull_request:
    branches:
      - main  # Run validation when a pull request targets the main branch

jobs:
  validate_sha256:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run SHA256 Validation
        run: |
          python validating.py
